### ISSUE TITLE
Menu is very broken

### ISSUE THREAD

**Issue by vorvek** [DylanHalstead/PolyChord-Website#4]
I have to assume the current menu is a bit of a placeholder so I have not done any responsive work on it. In the desktop view, the elements with submenus are lower than the rest of the menu, and there's some extra space that makes it impossible to move the mouse over the subelements without coming out of the hover event, thus closing the submenu. In smaller resolutions, the elements are superimposed, clicking the submenu clicks on the main menu, and things like that.

I can rework the whole menu, including the normal, desktop version, and make it more functional.

I'm not sure if you are using a particular tool to create the pages, or at this point you are using some IDE, but I'd suggest turning the files into PHP scripts so that we can split the head, header and footer out of each page. It will make maintaining the site much easier, as adding a page, for example, won't require going to each and single page and adding a link to its menu HTML.

**Comment by DylanHalstead** [comment]
I've never used Php but I'm not opposed to creating it in this way. I've only developed web apps through a python microframework (Flask), but being that this was just a static site I assumed using straight-up HTML wouldn't be an issue (but now I can see it def is). The issue with the menu is because of screen size/res, I have those dropdown elements placed using absolute positioning, if we give the navbar a fixed height (instead of just width: 100vw without specifying a height), then the issue should be fixable. If you'd like to instead rework the navbar into something a bit must traditional (I'm not sure if the way I made it is how they're usually made), I'm perfectly fine with that

**Comment by vorvek** [comment]
It doesn't really require any particular positioning, although it can be used.

The files will work exactly the same if we change the html extension to php, but it will allow the php interpreter to, well, interpret the code blocks delimited by the <?php ?> tags. It will require, however, deployment to a PHP server, like camtech, the same to run it locally. If you haven't done it before, it's probably better if we leave it for later down the road, once the rest is done.

**Comment by vorvek** [comment]
I've built a new menu, with some simplified syntax. It's responsive and whatnot. I was trying to run a pull request, but something is now broken and can't create one 🤔

I get this:

GraphQL error: Head sha can't be blank, Base sha can't be blank, Head repository can't be blank, No commits between DylanHalstead:main and vorvek:main, Head ref must be a branch, not all refs are readable

Also, I can't fetch your latest commit. Might need to fork the repository again.

**Comment by DylanHalstead** [comment]
It mightve caused an issue once I went from public to private. It is weird It won't even let you pull. Try a git merge and see where it doesn't like the differences? If it'll let you pull go ahead and try just pushing to main rather than a pr. If all else fails like you said another fork might be the way to go

**Comment by vorvek** [comment]
I think I managed to push the proper changes. Let me know if anything looks wrong. I've only changed the menu in the index file, since the whole header will become a single include anyway.

**Comment by DylanHalstead** [comment]
Looks good! I'm going to try and add a bit on animation to make it less jittery but functionally it's spot on.
